### ISSUE TITLE
[BUG] Social icons are not clearly visible on GitHub dark mode

### ISSUE THREAD

**Issue by vikasganiga05** [CharalambosIoannou/CharalambosIoannou#3]
The social icons are not clearly visible on GitHub's dark theme. Appending `#gh-dark-mode-only` or `#gh-light-mode-only` to the end of an image url will define whether it's only shown to viewers using a light or a dark GitHub theme.

Click on this link to know more &rarr; [Specify theme context for images in Markdown](https://github.blog/changelog/2021-11-24-specify-theme-context-for-images-in-markdown/)

**Screenshot**

![image](https://user-images.githubusercontent.com/74750414/165115725-0b490e25-919d-43da-a7a0-af85ab84aff6.png)

**Comment by CharalambosIoannou** [comment]
Thank you for the input. I am aware of this issue but I don't think it can be fixed since I need to embed a URL in the image as well. So while this does work:

```
![GitHub-Mark-Light](https://user-images.githubusercontent.com/3369400/139447912-e0f43f33-6d9f-45f8-be46-2df5bbc91289.png#gh-dark-mode-only)![GitHub-Mark-Dark](https://user-images.githubusercontent.com/3369400/139448065-39a229ba-4b06-434b-bc67-616e2ed80c8f.png#gh-light-mode-only)
```
there is no way that I know of to add a URL to the image to point to the required location.

Additionally, appending to the `<img>` tag of the existing HTML code with the `#gh-dark-mode-only` or `#gh-light-mode-only` again does not work. What I mean is:

Having this line
```
<img src="https://user-images.githubusercontent.com/45453951/165554834-4eeb2ac6-42d4-4431-baea-2f94ef6ec77b.png" 
```
or this line:
```
<img src="https://user-images.githubusercontent.com/45453951/165554834-4eeb2ac6-42d4-4431-baea-2f94ef6ec77b.png#gh-light-mode-only" 
```
does not show or hide the icon depending on dark/light mode because the image is wrapped in an HTML element.

**Comment by CharalambosIoannou** [comment]
Fixed by changing icons with color
